version: '3.1'

services:
  pg:
    image: postgres:11
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: example
      POSTGRES_USER: example-admin
      POSTGRES_PASSWORD: example-pass
    volumes:
      - ./examples/petstore/init.sql:/docker-entrypoint-initdb.d/petstore.sql
      - ./examples/split/init.sql:/docker-entrypoint-initdb.d/split.sql
      - ./examples/data-loader/init.sql:/docker-entrypoint-initdb.d/data-loader.sql
      - ./packages/laminar/init.sql:/docker-entrypoint-initdb.d/laminar.sql

  zookeeper:
    image: confluentinc/cp-zookeeper:5.2.2
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:5.5.3
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_HOST://localhost:29092

  schema-registry:
    image: confluentinc/cp-schema-registry:5.5.3
    depends_on:
      - zookeeper
      - broker
    ports:
      - 8081:8081
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper:2181'
