version: '3.1'

services:
  examples-db:
    image: postgres:11
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: example
      POSTGRES_USER: example-admin
      POSTGRES_PASSWORD: example-pass
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
